### ISSUE TITLE
Update store redesign

### ISSUE THREAD

**Issue by MarinPostma** [meilisearch/transplant#114]
The current design of the update store, with one update store per index is quite problematic:
- 1) It is complicated to make snapshot of, and require awkward locking mechanism
- 2) It sends updates in parrallel, but they are actually processed sequentially by the index actor, so multiple update nay be labelled as `processing`, while only one really is.

All the updates could be handled by a single update store to make things a lot easier to work with. It would also remove the need for a `write` channel in the `IndexActor` and simplify the code.

**Comment by curquiza** [comment]
Is it mandatory for the v0.21.0? 🙂

**Comment by MarinPostma** [comment]
Uhm yes I think

**Comment by MarinPostma** [comment]
I think I can do it reasonably fast
