### ISSUE TITLE
asc/desc behavior

### ISSUE THREAD

**Issue by curquiza** [meilisearch/transplant#117]
Compared to the old MeiliSearch, the custom ranking rules (`asc`/`desc`):
- need to know the field type. Maybe in `attributesForFaceting` -> TBD
- cannot work on strings -> this is the current behavior, might be enable but would involved warnings in the docs.

**Comment by curquiza** [comment]
I put the `breaking` label because, in any case, it would involve changes in the docs. Once the decision has been made, I will detail here how the custom ranking rules behavior is.

**Comment by curquiza** [comment]
Rectification: the custom ranking rules with the old MeiliSearch already do not work with strings: https://docs.meilisearch.com/reference/features/settings.html#custom-ranking-rule

**Comment by curquiza** [comment]
For the moment, and contrary to the current MeiliSearch: documents that don't have the Asc/Desc criterion attribute in their definition will no more be returned, not even after the documents that have this attribute.
We should discuss it.

**Comment by Kerollmops** [comment]
> The old MeiliSearch returns documents even if the field in `asc`/`desc` is not present and puts it at the end of the hits.

Not quite sure about that, I think the old MeiliSearch is returning the documents that don't have this field **at the end of the `asc`/`desc` bucket**

This is different in the sense that if the criterion is not at the end it will return documents that don't even have the field **before** documents that have it.

**Comment by curquiza** [comment]
Closed in favor of https://github.com/meilisearch/milli/issues/161 in Milli.
I also remove the `breaking` label since nothing will change on the user side.
