### ISSUE TITLE
New data types with Milli

### ISSUE THREAD

**Issue by curquiza** [meilisearch/transplant#118]
_I put this issue in transplant so that everyone can see the breaking change in the board, but it does not involve any change in transplant_

Here are the types handled by the old MeiliSearch in our docs: https://docs.meilisearch.com/reference/under_the_hood/datatypes.html

@Kerollmops, if there is any wrong explanation on this docs page can you please take the time to describe what is wrong in this issue so that @react-learner will be able to modify the docs accordingly? 😇

(If there is no change, I will close the issue of course)

**Comment by Kerollmops** [comment]
Here is a short list of things I think can be important, but I will also let @MarinPostma add its own list concerning Transplant:
 - Highlights tags (default to `<em>`) support more JSON types. The engine now adds highlight tags in JSON objects, array, strings, but tags can only be inserted inside strings. Therefore numbers and booleans are always not highlighted.
 - Documents ids are always converted into strings and compared this way. Note that documents are never altered and returned the way they were received.

**Comment by curquiza** [comment]
The tokenizer has not changed since the v0.20.0 🙂 Except if someone says there are big changes, it should be ok!

**Comment by curquiza** [comment]
> Highlights tags (default to <em>) support more JSON types. The engine now adds highlight tags in JSON objects, array, strings, but tags can only be inserted inside strings. Therefore numbers and booleans are always not highlighted.

MeiliSearch v0.20.0 did not handle highlight for arrays, but it was not documented, so no breaking

> Documents ids are always converted into strings and compared this way. Note that documents are never altered and returned the way they were received.

Does not impact the users, and v0.20.0 does not alter the documents as well

> The engine supports three content types: JSON, JSON Streaming, and CSV. Fields are converted into the appropriate type when faceted, if the conversion fails, an error is raised, and the full update is aborted.

These features are planned for the future version and have dedicated specs 

Since there is no "concrete" change for the user, I close this issue! Thanks for the details kero!
