### ISSUE TITLE
New known limitations

### ISSUE THREAD

**Issue by curquiza** [meilisearch/transplant#119]
_I put this issue in transplant so that everyone can see the breaking change in the board, but it does not involve any change in transplant_

Here are the known limitations handled by the old MeiliSearch in our docs: https://docs.meilisearch.com/reference/features/known_limitations.html#known-limitations

@Kerollmops, if there is any change on this docs page can you please take the time to describe what changed in this issue so that @react-learner will be able to modify the docs accordingly? 😇

This is ok to not know every limitation for the moment, in this case, we still need to know to remove them from the docs.

(If there is no change, I will close the issue of course)

**Comment by Kerollmops** [comment]
Here is a non-exhaustive list of the known limitations of milli. I will let @MarinPostma add its own list for the limitations of Transplant itself:

 - The number of query words is currently not limited, but it should reduce the possibility of server DDoSing.
 - The database size is always size limited, but as milli now only support one index, the engine can be more accurate, and each index can be set a max-size.
 - The number of indexes is no more hard-limited as milli supports only one index. Transplant is now free of using any adapted method to store the milli indexes.
 - The maximum words per attribute are limited in the same way as before, which is, to be more accurate, is limited in the number of possible word positions: words appear at positions and when two words are delimited by a hard separator (e.g. `.`, `!`), the word on the right it "pushed" by 8. Those positions are what is limited to 1000, not the count of words.
 - The payload size is no more limited by milli, and Transplant, IIRC, does not use LMDB to store user update content and therefore is no more limited to update of 2GiB.

**Comment by curquiza** [comment]
Thanks @Kerollmops!
We are waiting for the Transplant's limitations with @MarinPostma 🙂
@react-learner: we will create a list that gathers the Marin and Kero limitations so that it's easier for you to work with.

**Comment by MarinPostma** [comment]
- Each index is now contained in one db. This means that the `--max-mdb-size` and `--max-udb-size` are now **per index**. The `mac-udb-size` will be global as soon as I have finished with the updat store refactor.
- All write willll potentially become asynchronous, **this include index creation** (meilisearch HA)
- We can set indexing options (indexing thread, max RAM usage etc...), but these are not (yet) exposed to the user, and the default are probably not good.
- AOT json validation will probably need to be dropped


Appart for that, I think we are relatively ISO with legacy meilisearch. If I think of anyhting else, I will update this response

**Comment by curquiza** [comment]
Hey @meilisearch/docs-team, this message is the one you should look at to write the docs regarding the change in v0.21.0

Here is the final list of changes (related to limits) that impact the docs, e.g. that needs to be fixed in the docs:
- now, the size of the DB is per index, the flag changed. See https://github.com/meilisearch/transplant/issues/206 which is already a breaking issue
- number max of index -> there is no more limitation.

The other limits on [this page](https://docs.meilisearch.com/reference/features/known_limitations.html#design-limitations) stay unchanged.

Here is the list of the limits that are not in your docs (sorry if I'm wrong) but you might want to document it, it's up to you!
- The values of the filterable attributes are limited to 500 bytes. Ex: `{ "author": "Jane Austen" }` where `author` is a `filterableAttributes` -> "Jane Austen" is the value and can't be more than 500 bytes, e.g 500 ASCII characters.
- The total number of documents in a single index is limited to 4 294 967 296.

**Comment by curquiza** [comment]
Closing this issue then, with the `breaking` label
