### ISSUE TITLE
Commit SHA and commit date still wrong

### ISSUE THREAD

**Issue by curquiza** [meilisearch/transplant#137]
Despite this PR (https://github.com/meilisearch/transplant/pull/129), the commit SHA is still `UNKNOWN`, and the commit date does not correspond to the commit date:

<img width="1464" alt="Capture d’écran 2021-04-08 à 18 37 01" src="https://user-images.githubusercontent.com/20380692/114064084-927cc200-9899-11eb-9474-df62b1bcdc17.png">

@shekhirin, maybe do you know how to fix this since it was your PR? 🙂 Feel free to ask any question, I maybe don't understand something.

**Comment by shekhirin** [comment]
Maybe you've built the image without needed build args? An example of correct image building was in the PR https://github.com/meilisearch/transplant/pull/129

**Comment by curquiza** [comment]
I use the image that has been published via the CI (`.github/workflows/publish_to_docker.yml`) updated in the PR #129.
The CI is maybe not adapted yet.

**Comment by shekhirin** [comment]
Ah ok got it. I'll look into the problem and try to reproduce it, thanks!

**Comment by curquiza** [comment]
You're awesome!! Tell me if I can help!

**Comment by shekhirin** [comment]
Haha the problem appears to be really obvious and I spent several hours trying to fix it in GitHub Actions for nothing lol.

My PR fixed the commit sha & date for `/version` endpoint, not the startup message 🙂  
https://github.com/meilisearch/transplant/blob/6e1ddfea5a7af1184c7baec8b977da0157215990/meilisearch-http/src/routes/stats.rs#L59-L66

I'll make another PR that uses new env vars in there too.
https://github.com/meilisearch/transplant/blob/0344cf5874fce9928d4b8fd57a946b81972afdce/meilisearch-http/src/main.rs#L119-L123

Thanks for the issue!

**Comment by curquiza** [comment]
Oh my bad, I should have checked this before doing the issue, it might have helped you! 🤦‍♀️ 
Thanks for your PR @shekhirin! 😁
