### ISSUE TITLE
filter syntax

### ISSUE THREAD

**Issue by curquiza** [meilisearch/transplant#140]
Now the `filter` parameter can accept both syntaxes: array or string.

Cf the spec for more details: https://github.com/meilisearch/specifications/blob/main/text/0027-filter-and-facet-behavior.md

**Comment by curquiza** [comment]
⚠️ I updated the issue, the parameter `filters` is now `filter`.

**Comment by gmourier** [comment]
> Now the `filter` parameter can accept both syntaxes: array or string.
> 
> Cf the spec for more details: https://github.com/meilisearch/specifications/pull/27/files

We also added that the filter parameter can use a mixed syntax made of array and string syntaxes.
