### ISSUE TITLE
Warn users about telemetry

### ISSUE THREAD

**Issue by curquiza** [meilisearch/transplant#141]
Related to this issue: https://github.com/meilisearch/MeiliSearch/issues/1334

Checked with @gmourier, we don't need to ask for the consent of the users, but it might be nice to warn them the telemetry is activated and which flag to use to deactivate it.

FIY, MeiliSearch already warns the users about the telemetry, but not how to disable it:

<img width="877" alt="Capture d’écran 2021-04-12 à 18 11 54" src="https://user-images.githubusercontent.com/20380692/114427299-3e385180-9bbb-11eb-9ecb-65f82cbccc72.png">

I put the `breaking` label because it will change the MeiliSearch display during the launch

@gmourier, we are waiting for the product team to know how to handle properly this warning. If you think it does not need a spec, you can answer in this issue :)

**Comment by gmourier** [comment]
Thanks for the follow-up @curquiza. It can have a consequent impact on many levels so I suggest gathering to take a decision. Not sure if it needs a spec at this point.

**Comment by gmourier** [comment]
Specification started here https://github.com/meilisearch/specifications/pull/34

**Comment by curquiza** [comment]
Close this issue in favor of #180
