### ISSUE TITLE
documents without primary key should not be able to be added

### ISSUE THREAD

**Issue by curquiza** [meilisearch/transplant#165]
Currently, if I add documents without any primary key, transplant accepts the documents and there are stored in the DB.

Steps:

Add:
```json
[
  { "title": "Pride and Prejudice"}
]
```

Then call `indexes/:uid/documents`:

```json
[
    {
        "title": "Pride and Prejudice"
    }
]
```

⚠️ Tests should be added:
- add documents: the primary key (not `id`, but should contain `id` in the attribute name) can be inferred.
- same for update documents
- add documents: the primary key can be passed as parameter (don't use an attribute with `id` in the attribute name)
- same for update documents
- cannot add documents without primary key
- cannot update documents without primary key

**Comment by Kerollmops** [comment]
This should be highly related to [this line in the milli indexer](https://github.com/meilisearch/milli/blob/3bcc1c0560857163968500169ac73385be3b9d5d/milli/src/update/index_documents/mod.rs#L311-L313), we should maybe change [the default setting to not generate the documents ids by default](https://github.com/meilisearch/milli/blob/3bcc1c0560857163968500169ac73385be3b9d5d/milli/src/update/index_documents/mod.rs#L294).

**Comment by gmourier** [comment]
Do we need a specification for this behavior? Maybe it can be useful to auto-generate ids for some use cases. However, it remains a hypothesis, I can only think of time-series but this is not the direct target of Meilisearch and the id could be the timestamp.

**Comment by curquiza** [comment]
This behavior can be reconsidered, but not for the v0.21.0 :) It would impact the documentation and the way of using MeilISearch a lot.

Also, I got feedback from Algolia users that hate the auto-generated ids 🙂

**Comment by curquiza** [comment]
Done on milli side!
