### ISSUE TITLE
_formatted and attributesToRetrieve behavior

### ISSUE THREAD

**Issue by curquiza** [meilisearch/transplant#168]
We need to define the behavior of the search response when using `attributesToRetrieve` + `attributesToHighlight`/`attributesToCrop`: which attributes should be present in the `_formatted` or not?

Example of different usecases: which attributes should we return in the `_formatted` and outside the `_formatted`?

```json
{
    "q": "",
    "attributesToRetrieve": ["author"],
    "attributesToHighlight": ["author", "title"]
}
```

```json
{
    "q": "",
    "attributesToRetrieve": ["author"],
    "attributesToHighlight": ["title"]
}
```

```json
{
    "q": "",
    "attributesToRetrieve": ["author"],
    "attributesToHighlight": ["*"]
}
```

```json
{
    "q": "",
    "attributesToRetrieve": ["*"], // equivalent to no attributesToRetrieve defined
    "attributesToHighlight": ["author"]
}
```

This list is not exhaustive.

The behavior of MeiliSearch v0.20.0 is not a source of truth. Example of inconsistent behavior in MeiliSearch v0.20.0: https://github.com/meilisearch/MeiliSearch/issues/897

⚠️ Only the attributes in `displayedAttributes` can be displayed in the search response, no matter are the attributes in `attributesToRetrieve`, `attributesToHighlight`, and `attributesToCrop`

**Comment by gmourier** [comment]
Specification started at meilisearch/specifications#39

**Comment by curquiza** [comment]
Replaced by #203
