### ISSUE TITLE
Implement error handling

### ISSUE THREAD

**Issue by MarinPostma** [meilisearch/transplant#17]
Error handling has been ignored until now, it must be implemented

**Comment by curquiza** [comment]
Are you waiting for milli to implement this?

**Comment by MarinPostma** [comment]
Yes, right now I'm not getting usable error types back from milli

**Comment by curquiza** [comment]
Waiting for https://github.com/meilisearch/milli/issues/109

**Comment by curquiza** [comment]
Should implement the current errors in the docs: https://docs.meilisearch.com/errors/#meilisearch-errors

If some are added or removed, please let us know on this issue

**Comment by curquiza** [comment]
I put the `breaking` label for the @meilisearch/docs-team. The following errors should not be present in the docs anymore (not used because not relevant for the new search engine)
- `invalid_facet`
- `missing_header`
- `search error`
- `bad parameter`

**Comment by curquiza** [comment]
Closed by #210
