### ISSUE TITLE
Integrate telemetry

### ISSUE THREAD

**Issue by curquiza** [meilisearch/transplant#180]
Related to this spec: https://github.com/meilisearch/specifications/pull/34/files
Replaces #141 

----

Integrate telemetry (Amplitude) in the same way this is already implemented in MeiliSearch v0.20.0 except:
- [x] we need to use [`http-api-v2` of Amplitude](https://developers.amplitude.com/docs/http-api-v2). The current version of `http-api` in MeiliSearch is deprecated.
- [x] the Sentry and Amplitude errors should fail silently
- [x] the flag `--no-sentry` and the variable `MEILI_NO_SENTRY` are removed. Now, the flag `--no-analytics` (env vraiable `MEILI_NO_ANALYTICS`) disables Amplitude AND Sentry at the same time.
- [x] When launching MeiliSearch by default, the telemetry is still enabled but the following message should be present (decided in the spec above):
```text
...
Commit SHA:		"def1596eaf95c56a964399c4e5ae0875e0b155ee"
Commit date:		"2021-06-15"
Package version:	"0.21.0-alpha.4"

Thank you for using MeiliSearch!

We collect anonymized analytics to improve our product and your experience. To learn more, including how to turn off analytics, visit our dedicated documentation page: https://docs.meilisearch.com/reference/features/configuration.html#analytics

Anonymous telemetry: "Enabled"

Documentation:		https://docs.meilisearch.com
Source code:		https://github.com/meilisearch/meilisearch
...
```

- [X] If the telemetry is disabled, here is the following message 
```text
...
Commit SHA:		"def1596eaf95c56a964399c4e5ae0875e0b155ee"
Commit date:		"2021-06-15"
Package version:	"0.21.0-alpha.4"
Anonymous telemetry:    "Disabled"

Documentation:		https://docs.meilisearch.com
Source code:		https://github.com/meilisearch/meilisearch
...
```

- [X]  Remove the possibility to choose the sentry server

I put the `breaking` label for the docs team (@react-learner) because:
- the message will change when starting MeiliSearch, so the screenshot might be obsolete 🙂 
- the flag `--no-sentry` and the variable `MEILI_NO_SENTRY` are removed. Cf third point of this issue (related to #204)

- [X] Deactivate the collection of analytics in debug build

**Comment by react-learner** [comment]
I proposed a small change to the CLI message over in the Telemetry spec: https://github.com/meilisearch/specifications/pull/34#discussion_r627351546

**Comment by curquiza** [comment]
Issue update 😊 Thanks @react-learner!

**Comment by qdequele** [comment]
just to avoid that sentry burns by the number of requests that we send them. Can we please stop logging all the errors that come from LMDB.

**Comment by gmourier** [comment]
@qdequele To be more precise are we speaking about those ones? 

```actix_http::response actix_http::response::Response::from_error
Internal Server Error: ResponseError { inner: Heed(Mdb(MapFull)) }```

**Comment by irevoire** [comment]
I mostly finished the implementation and I was wondering. I'm still supposed to print these two lines : 
```
Sentry DSN:		"https://5ddfa22b95f241198be2271aaf028653@sentry.io/3060337"
Anonymous telemetry:	"Enabled"
```

And if yes in which order would you like things to appear? Currently it's ~~ugly~~ like that : 
```
Database path:		"./data.ms"
Server listening on:	"http://127.0.0.1:7700"
Environment:		"development"
Commit SHA:		"b119bb4ab00f94348b64f01411c4359dee237385"
Commit date:		"2021-06-14"
Package version:	"0.21.0-alpha.4"
Thank you for using MeiliSearch! We collect anonymized analytics to improve our product and your experience. To learn more, including how to turn off analytics, visit our dedicated documentation page: https://docs.meilisearch.com/reference/features/configuration.html#analytics
Sentry DSN:		"https://5ddfa22b95f241198be2271aaf028653@sentry.io/3060337"
Anonymous telemetry:	"Enabled"

No master key found; The server will accept unidentified requests. If you need some protection in development mode, please export a key: export MEILI_MASTER_KEY=xxx

Documentation:		https://docs.meilisearch.com
Source code:		https://github.com/meilisearch/meilisearch
Contact:		https://docs.meilisearch.com/resources/contact.html or bonjour@meilisearch.com
```

**Comment by irevoire** [comment]
I'll stop logging the errors that come from LMDB in another PR because I have no idea how to do it currently, and in the code, it's unrelated to `amplitude`.

**Comment by gmourier** [comment]
> I mostly finished the implementation and I was wondering. I'm still supposed to print these two lines :
> 
> ```
> Sentry DSN:		"https://5ddfa22b95f241198be2271aaf028653@sentry.io/3060337"
> Anonymous telemetry:	"Enabled"
> ```
> 
> And if yes in which order would you like things to appear? Currently it's ~ugly~ like that :
> 
> ```
> Database path:		"./data.ms"
> Server listening on:	"http://127.0.0.1:7700"
> Environment:		"development"
> Commit SHA:		"b119bb4ab00f94348b64f01411c4359dee237385"
> Commit date:		"2021-06-14"
> Package version:	"0.21.0-alpha.4"
> Thank you for using MeiliSearch! We collect anonymized analytics to improve our product and your experience. To learn more, including how to turn off analytics, visit our dedicated documentation page: https://docs.meilisearch.com/reference/features/configuration.html#analytics
> Sentry DSN:		"https://5ddfa22b95f241198be2271aaf028653@sentry.io/3060337"
> Anonymous telemetry:	"Enabled"
> 
> No master key found; The server will accept unidentified requests. If you need some protection in development mode, please export a key: export MEILI_MASTER_KEY=xxx
> 
> Documentation:		https://docs.meilisearch.com
> Source code:		https://github.com/meilisearch/meilisearch
> Contact:		https://docs.meilisearch.com/resources/contact.html or bonjour@meilisearch.com
> ```

Good questions @irevoire.

Regarding the Sentry DSN line, I don't think it provides much useful information to the user. I would remove it knowing that its usage is now included in the analytics flag.

I think we need to keep the `Anonymous telemetry:` line. The message should be displayed when the value of analytics is "enabled". 

Finally I would have made a section dedicated to analytics by spacing it from other blocks to put it more in front. Something like that.

> ```
> Database path:		"./data.ms"
> Server listening on:	"http://127.0.0.1:7700"
> Environment:		"development"
> Commit SHA:		"b119bb4ab00f94348b64f01411c4359dee237385"
> Commit date:		"2021-06-14"
> Package version:	"0.21.0-alpha.4"
>
> Thank you for using MeiliSearch! We collect anonymized analytics to improve our product and your experience. To learn more, including how to turn off analytics, visit our dedicated documentation page: https://docs.meilisearch.com/reference/features/configuration.html#analytics
>
> Anonymous telemetry:	"Enabled"
> 
> No master key found; The server will accept unidentified requests. If you need some protection in development mode, please export a key: export MEILI_MASTER_KEY=xxx
> 
> Documentation:		https://docs.meilisearch.com
> Source code:		https://github.com/meilisearch/meilisearch
> Contact:		https://docs.meilisearch.com/resources/contact.html or bonjour@meilisearch.com
> ```

**Comment by irevoire** [comment]
Currently a user can override the default sentry dsn user. So I would expect that we either remove this option from the command line or we keep the line displaying the current used dsn. What do you think?

**Comment by gmourier** [comment]
Good point @irevoire. Didn't expected the override of the sentry dsn capability from the documentation https://docs.meilisearch.com/reference/features/configuration.html#options.

We should remove it as we are removing `MEILI_NO_SENTRY` and `--no-sentry`.

**Comment by curquiza** [comment]
Ok, can you update the spec @gmourier according to this new points? :)

**Comment by gmourier** [comment]
> Ok, can you update the spec @gmourier according to this new points? :)

Done!

**Comment by curquiza** [comment]
I've updated the issue with the new points :)

**Comment by curquiza** [comment]
I reopen this issue:
- `--no-analytics` flag is not available
- the display when launching MeiliSearch is not the one described in this issue

**Comment by curquiza** [comment]
The issue was not up-to-date: the collection of analytics is deactivated in dev mode.
When compiling from the source files, you need to use the `--release` flag.

It perfectly works!
I close the issue
