### ISSUE TITLE
Paginate update list

### ISSUE THREAD

**Issue by MarinPostma** [meilisearch/transplant#184]
When querying `/indexes/:name/updates` all the updates are returned. This is problematic if there are a lot of updates, and we should prefer paging the result, and return a default maximum number of updates.

@gmourier  @curquiza

**Comment by gmourier** [comment]
Nice spot @MarinPostma. How many items by default would be best for updates according to you?

**Comment by MarinPostma** [comment]
20?

**Comment by curquiza** [comment]
Closed in favor of specifications
