### ISSUE TITLE
Add 2021 to license year

### ISSUE THREAD

**Issue by fharper** [meilisearch/transplant#2]
I'll create a GitHub action for next years.

**Comment by curquiza** [comment]
This repo will be removed once merged into MeiliSearch. Closing the issue then

**Comment by fharper** [comment]
So during that time, people can use the code and do whatever we want if the license year isn't updated. There is a legal reason behind those requests (probably take us more time closing the issue than doing the PR to change it) :D

**Comment by fharper** [comment]
I was going to do the PR, but it's already 2021 in the LICENSE.md file... 😬
