### ISSUE TITLE
implement dumps

### ISSUE THREAD

**Issue by MarinPostma** [meilisearch/transplant#20]
- https://docs.meilisearch.com/reference/api/dump.html#dumps
- https://docs.meilisearch.com/reference/features/dumps.html#dumps

**Comment by curquiza** [comment]
The dump implementation should fix this bug: https://github.com/meilisearch/MeiliSearch/issues/1241

**Comment by curquiza** [comment]
This issue should fix this issue: https://github.com/meilisearch/MeiliSearch/issues/999
I put the breaking label because of this change that impacts the documentation
