### ISSUE TITLE
Rename MAX_MDB_SIZE into MAX_INDEX_SIZE

### ISSUE THREAD

**Issue by curquiza** [meilisearch/transplant#206]
Related to this spec: https://github.com/meilisearch/specifications/pull/48/files

- [x] Rename `--max-mdb-size` to `--max-index-size`
- [x] Rename `MAX_MDB_SIZE` to `MEILI_MAX_INDEX_SIZE`

Also, related to this issue: #204

**Comment by curquiza** [comment]
@meilisearch/docs-team for this change

**Comment by dichotommy** [comment]
In order to be consistent with the other env variables, should it be `MEILI_MAX_INDEX_SIZE`? Or do we feel that that is too long?

**Comment by irevoire** [comment]
Yes, I thought that was implied since everything else is `MEILI_*`. And that's what I implemented.

**Comment by gmourier** [comment]
My bad, I forgot to prefix with `MEILI_` the env var in the specification but it should follow the actual convention! I will fix the specification! Thanks guys!

**Comment by curquiza** [comment]
I've updated the issue accordingly :)
