### ISSUE TITLE
Reset settings with sub-settings routes

### ISSUE THREAD

**Issue by curquiza** [meilisearch/transplant#225]
With sub-settings routes (ex: `/indexes/:uid/settings/displayed-attribute`):
- reset settings with sub-settings routes, the new default value should be put to its default value ([see the docs for the different default values](https://docs.meilisearch.com/reference/features/settings.html#settings))
- get the settings with the general settings routes -> the new value is taken into account -> ok
- get the settings with the subsettings route -> get `null` for searchable attributes and displayed attribute instead of `["*"]`

⚠️ Add tests

**Comment by MarinPostma** [comment]
fixed, this was due to the way @tamo and I serialized the settings.
