### ISSUE TITLE
facetsDistribution does not return 0 values

### ISSUE THREAD

**Issue by curquiza** [meilisearch/transplant#234]
This issue is not to implement anything but just to inform the @meilisearch/docs-team and the @meilisearch/integration-admin-team for the tests
Also @CaroFG and @gmourier it might interest you to respond to the user feedbacks

Before (v0.20) with this set of documents;:
```json
[
  { "id": 2,    "title": "Pride and Prejudice", "genre": "romance" },
  { "id": 456,  "title": "Le Petit Prince", "genre": "adventure" },
  { "id": 1,    "title": "Alice In Wonderland", "genre": "fantasy" },
]
```

And this search:
```json
{
    "q": "prince",
    "facetsDistribution": ["genre"]
}
```

I got this `facetsDistribution`:

```json
"facetsDistribution": {
        "genre": {
            "adventure": 1,
            "fantasy": 1,
            "romance": 0
        }
    },
```

Now, in v0.21 with the same set of documents and the same search, I get:

```json
"facetsDistribution": {
        "genre": {
            "adventure": 1,
            "fantasy": 1
        }
    },
```

=> the `0` values are not present anymore. For performance reasons. Since it's complicated to change it for the v0.21, we let this breaking but we might have user complaints. Some of them already asked to remove the `0` value from `facetsDistribution` but I'm not aware of the part that wants to keep the `0` value.

**Comment by curquiza** [comment]
I close immediately this issue since nothing has to be done in transplant.

**Comment by CaroFG** [comment]
Thank you for the info @curquiza 🙂

**Comment by dichotommy** [comment]
Yes thank you @curquiza !

To be clear: the intention is to leave it this way, right? This isn't a case where we're planning or hoping to implement the previous behavior in v0.22+?

**Comment by curquiza** [comment]
It depends on user's feedback and what @gmourier prioritizes.

**Comment by gmourier** [comment]
Hello! 

Concerning the user feedbacks, we already have some that support this choice. Some find it counterintuitive for the user experience when browsing by facet. I add in the product backlog an issue on this subject, we could propose a parameter to choose between a disjunctive or conjunctive method if we have feedbacks that also ask to have `0`.

**Comment by curquiza** [comment]
And of course, sorry for noticing you only now: I've just found out about this change, and @Kerollmops told me it would not be easy to change before the RC release next week.

**Comment by gmourier** [comment]
I have 0 problems with that, we adapt, the knowledge is shared, I understand that the RC forces us to make quick choices. I think that this one goes in the right direction, time will tell 😇
