### ISSUE TITLE
`exhaustiveFacetsCount` is not implemented

### ISSUE THREAD

**Issue by curquiza** [meilisearch/transplant#236]
This issue is not to implement anything but just to inform the @meilisearch/docs-team and the @meilisearch/integration-team (for the test part)
Also @CaroFG and @gmourier it might interest you to answer to the user feedbacks

In v0.20.0, `exhaustiveFacetsCount` can be `false` or `true` (contrary to `exhaustiveNbHits` that is always `false` even in v0.20.0).

In v0.21.0, `exhaustiveFacetsCount` is not implemented. It means, it will always return `false` (as `exhausitveNbHits`). We want to release it without this implementation since it would have taken too much time and would delay the v0.21.0 release.

I've never heard about users using this feature but @gmourier it can still interest you to keep it back 🙂

**Comment by curquiza** [comment]
I close immediately this issue since it does not involve any implementation in transplant

**Comment by gmourier** [comment]
Thanks for the information @curquiza. Let's give it a shot and see if it's important for some users!
