### ISSUE TITLE
Mini dashboard and API key

### ISSUE THREAD

**Issue by curquiza** [meilisearch/transplant#245]
When running with

```bash
cargo run --release -- --master-key=masterKey
```

The mini-dashboard tells me:

<img width="1200" alt="Capture d’écran 2021-06-28 à 10 56 12" src="https://user-images.githubusercontent.com/20380692/123608893-784ee200-d7ff-11eb-89ad-b2ba2814b95c.png">

It seems coming from transplant since @mdubus and I tested the mini-dashboard from source https://github.com/meilisearch/mini-dashboard and with 

```bash
cargo run --release --no-default-features -- --master-key=masterKey
```

and it works

**Comment by irevoire** [comment]
Look like we need a new release of the mini-dashboard. Once it's done @mdubus, you can ping me, and I'll update transplant accordingly :smile:

**Comment by mdubus** [comment]
Done, just linked the PR to this issue 😉

**Comment by irevoire** [comment]
Thank you!
