### ISSUE TITLE
Define list index order

### ISSUE THREAD

**Issue by MarinPostma** [meilisearch/transplant#50]
When performing a `list_index` operation, the order of the elements of the returned array is undefined.

possible sorting strategy:
- creation date
- last update date
-  uid

**Comment by tpayet** [comment]
Thanks for bringing this, we opened meilisearch/specifications#19 which will be resolved for v1.

For v0.21 could we keep the actual behavior in order to minimize changes for the upcoming release of the new engine?

If yes, feel free to re-label this issue :)

**Comment by curquiza** [comment]
I close this issue then!
