### ISSUE TITLE
No attributes to retrieve on `/documents/{id}`

### ISSUE THREAD

**Issue by MarinPostma** [meilisearch/transplant#52]
Contrary to `GET /documents`, `GET /documents/{id}` does not have a `attributesToRetrieve` parameter, I could be desirable to introduce this argument to be consistent with the former.

**Comment by tpayet** [comment]
Thanks for bringing this, we opened meilisearch/specifications#9 which will be resolved for v1.

For v0.21 could we keep the actual behavior in order to minimize changes for the upcoming release of the new engine?

If yes, feel free to re-label this issue :)

**Comment by curquiza** [comment]
I close this issue then!
