### ISSUE TITLE
Update response format (push/update/delete docs or update/delete settings)

### ISSUE THREAD

**Issue by curquiza** [meilisearch/transplant#64]
After pushing/updating/deleting documents or updating/resetting documents, the answer contains additional information

v0.19.0

```jsx
{
    "updateId": 0
}
```

Alpha:

```jsx
{
  "status": "pending",
  "updateId": 0,
  "meta": {
    "type": "DocumentsAddition",
    "method": "UpdateDocuments",
    "format": "Json",
    "primary_key": null
  },
  "enqueuedAt": "2021-03-02T14:37:31.345931100Z"
}
```

Should we keep all this information?

EDIT: we want to come back to the previous behavior (v0.19.0)

**Comment by tpayet** [comment]
Thanks for bringing this, we opened meilisearch/specifications#12 which will be resolved for v1.

For v0.21 could we keep the actual behavior in order to minimize changes for the upcoming release of the new engine?

If yes, feel free to re-label this issue :)

**Comment by curquiza** [comment]
Issue description updated
