### ISSUE TITLE
Rename facetedAttributes to attributesForFaceting

### ISSUE THREAD

**Issue by curquiza** [meilisearch/transplant#65]
`attributesForFaceting` has been renamed into `facetedAttributes`.

Should we keep this new name?

**Comment by tpayet** [comment]
Thanks for bringing this, we opened meilisearch/specifications#15 which will be resolved for v1.

For v0.21 could we keep the actual behavior in order to minimize changes for the upcoming release of the new engine?

If yes, feel free to re-label this issue :)
