### ISSUE TITLE
Remove uuid from displayed index information

### ISSUE THREAD

**Issue by curquiza** [meilisearch/transplant#67]
When getting or creating an index:

v0.19.0:

```json
{
    "name": "indexUID",
    "uid": "indexUID",
    "createdAt": "2021-03-02T14:45:17.837494800Z",
    "updatedAt": "2021-03-02T14:45:17.838545700Z",
    "primaryKey": null
}
```

Alpha:

```json
{
  "uid": "indexUID",
  "uuid": "72114596-0807-4af4-9610-07fc2c957990",
  "createdAt": "2021-03-02T20:37:06.772799900Z",
  "updatedAt": "2021-03-02T20:37:06.772799900Z",
  "primaryKey": null
}
```

Should we keep the `uuid` field in the displayed information?

EDIT: Yes for the moment we remove `uuid` from the displayed information

**Comment by tpayet** [comment]
Thanks for bringing this, we opened meilisearch/specifications#20 which will be resolved for v1.

For v0.21 could we keep the actual behavior in order to minimize changes for the upcoming release of the new engine?

If yes, feel free to re-label this issue :)
