### ISSUE TITLE
Search with attributesToRetrieve and displayedAttributes

### ISSUE THREAD

**Issue by curquiza** [meilisearch/transplant#69]
- Add documents with `title` and `name` as fields
- Set `displayedAttribtues` as `name`
- Basic search without an `attributesToRetrieve` -> it only displays the `name` field -> OK and iso
- Now, search with `attributesToRetrieve` set as `['title', 'name']` -> it displays the `name` AND the `title` fields -> not iso. It should only display the `name` fields.

`attributesToRetrieve` should check what is present in the `displayedAttribtues` before displaying the fields.

**Comment by curquiza** [comment]
Sorry if it's already done (the PR #58) is too big, I'm not able to check if it has been added: can we add tests of this please?

**Comment by MarinPostma** [comment]
yes @curquiza, I haven't started writing tests for search just yet, adding it to #3.
