### ISSUE TITLE
implement distinctAttribute

### ISSUE THREAD

**Issue by MarinPostma** [meilisearch/transplant#7]

**Comment by curquiza** [comment]
Waiting for https://github.com/meilisearch/milli/issues/112

**Comment by curquiza** [comment]
Must be documented @react-learner 
FYI: To be iso, the users will be able to distinct without pass the field in the facets.
However, if they want performance, the users should pass the facets in the faceted attributes (in the settings).

**Comment by curquiza** [comment]
The usage will not be breaking for the user, I remove the `breaking` label

**Comment by react-learner** [comment]
@curquiza Is it still better for performance to add your `distinctAttribute` to the `attributesForFaceting` list?

**Comment by curquiza** [comment]
Nope, sorry, I've updated my comment!
There is no breaking change for the user usage 🙂 The changes are only internal.
