### ISSUE TITLE
Document push does not fail synchronously if JSON is invalid

### ISSUE THREAD

**Issue by curquiza** [meilisearch/transplant#71]
In the alpha, when the documents are pushed but the JSON is invalid, no error is thrown synchronously -> the user has to check the update status to know it failed.
It means the documents push/update routes never fail (synchronously)

It's not iso with the previous MeiliSearch but can be discussed.

**Comment by tpayet** [comment]
Thanks for bringing this, we opened meilisearch/specifications#21 which will be resolved for v1.

For v0.21 could we keep the actual behavior in order to minimize changes for the upcoming release of the new engine?

If yes, feel free to re-label this issue :)

**Comment by curquiza** [comment]
@MarinPostma can you tell us if it's easy to come back to the previous behavior?
