### ISSUE TITLE
Implement /stats and /indexes/:uid/stats

### ISSUE THREAD

**Issue by curquiza** [meilisearch/transplant#73]
- [ ] Implement /stats
- [ ] Implement /indexes/:uid/stats
- [ ] add tests

**Comment by curquiza** [comment]
waiting for https://github.com/meilisearch/milli/issues/113

**Comment by shekhirin** [comment]
I think I can continue working on the stats part as I've done some PRs in the milli repo.

Not quite sure what to do with `is_indexing` field for now, however I can mock it with constant `false` value.

**Comment by curquiza** [comment]
Hello @shekhirin! That's really nice! Maybe @MarinPostma can guide you on this? 🙂

**Comment by shekhirin** [comment]
Thanks! @MarinPostma I've just made a draft ☝️ , can you check it out and tell if the direction of work is right?

**Comment by curquiza** [comment]
We might check if it fixes this issue: https://github.com/meilisearch/MeiliSearch/issues/1257 😇
