### ISSUE TITLE
_formated is not returned anymore

### ISSUE THREAD

**Issue by MarinPostma** [meilisearch/transplant#75]
Right now, when transformation are requested on search results (highlight, crop), the transformation are done on the original document, whereas legacy meilisearch used to return both the original document, and a `_formated` version.

There has been talked some time ago to remmove the formated altogether, and avoid the useless sideloading of full documents.

The full documents can still be easily retrieved with the `indexes/:uid/documents/:id` route.

We can decide if we want this feature to stay in transplant.

**Comment by tpayet** [comment]
Thanks for bringing this, we opened meilisearch/specifications#17 which will be resolved for v1.

For v0.21 could we keep the actual behavior in order to minimize changes for the upcoming release of the new engine?

If yes, feel free to re-label this issue :)

**Comment by curquiza** [comment]
@MarinPostma Can you confirm this is easy to roll back to the previous behavior?

**Comment by MarinPostma** [comment]
It needs to be implemented and prioritized
