### ISSUE TITLE
Update status response

### ISSUE THREAD

**Issue by curquiza** [meilisearch/transplant#78]
We need to come back to the previous behavior of the v0.19.0, about the display of the update status when calling the `indexes/:uid/updates` and `indexes/:uid/updates/:id` routes:

Here is the expected response template:

```jsx
[
    {
        "status": "processed",
        "updateId": 0,
        "type": {
            "name": "DocumentsAddition",
            "number": 6
        },
        "duration": 0.0160523,
        "enqueuedAt": "2021-03-02T19:45:46.919402700Z",
        "processedAt": "2021-03-02T19:45:46.937445Z"
    }
]
```

Replaces #47 and #48

Docs link -> https://docs.meilisearch.com/reference/api/updates.html#example

**Comment by MarinPostma** [comment]
@irevoire, we should create a shim data structure to represent the reponse, and use the currently returned `UpdateStatus` to populate its data, it's a good first issue :)
