### ISSUE TITLE
Searching with offset returns an empty hits array

### ISSUE THREAD

**Issue by CaroFG** [meilisearch/transplant#82]
The following query: 

`curl 'http://localhost:7700/indexes/movies/search' \
  --data '{ "q": "shazam", "offset": 1 }'`

Returns the following response:

`{
  "hits": [],
  "nbHits": 3,
  "query": "shazam",
  "limit": 20,
  "offset": 1,
  "processingTimeMs": 1
}`

Expected behavior: hits array should contain 2 movies

**Comment by MarinPostma** [comment]
fixed by https://github.com/meilisearch/milli/pull/118
