### ISSUE TITLE
Searching with attributesToHighlight doesn't return the query word surrounded by tags 

### ISSUE THREAD

**Issue by CaroFG** [meilisearch/transplant#83]
On v0.19.0, the following query:

`curl 'http://localhost:7700/indexes/movies/search' \
  --data '{ "q": "ability", "attributesToHighlight": ["*"]}'`

Would return a result like this one: 

`    {
      "id": "102899",
      "title": "Ant-Man",
      "poster": "https://image.tmdb.org/t/p/w500/rQRnQfUl3kfp78nCWq8Ks04vnq1.jpg",
      "overview": "Armed with the astonishing ability to shrink in scale but increase in strength, master thief Scott Lang must embrace his inner-hero and help his mentor, Doctor Hank Pym, protect the secret behind his spectacular Ant-Man suit from a new generation of towering threats. Against seemingly insurmountable obstacles, Pym and Lang must plan and pull off a heist that will save the world.",
      "release_date": 1436835600,
      "genres": [
        "Documentary"
      ],
      "_formatted": {
        "id": "102899",
        "title": "Ant-Man",
        "poster": "https://image.tmdb.org/t/p/w500/rQRnQfUl3kfp78nCWq8Ks04vnq1.jpg",
        "overview": "Armed with the astonishing <em>ability</em> to shrink in scale but increase in strength, master thief Scott Lang must embrace his inner-hero and help his mentor, Doctor Hank Pym, protect the secret behind his spectacular Ant-Man suit from a new generation of towering threats. Against seemingly insurmountable obstacles, Pym and Lang must plan and pull off a heist that will save the world.",
        "release_date": 1436835600,
        "genres": [
          "Documentary"
        ]
      }
    }`

While the alpha version returns:

`    {
      "id": "10131",
      "title": "A Nightmare on Elm Street 4: The Dream Master",
      "poster": "https://image.tmdb.org/t/p/w500/boStYG7jKdoIZTduiOOsUVknD13.jpg",
      "overview": "Dream demon Freddy Krueger is resurrected from his apparent demise, and rapidly tracks down and kills the remainder of the Elm Street kids. However, Kristen, who can draw others into her dreams, wills her special ability to her friend Alice. Alice soon realizes that Freddy is taking advantage of that unknown power to pull a new group of children into his foul domain.",
      "release_date": 587955600,
      "genres": [
        "Horror",
        "Thriller"
      ]
    }`

v0.19.0 surrounds the matching query word 'ability' with \<em> tags, like this:  \<em>ability\</em>
Alpha version doesn't.

I would expect the alpha version to do the same (even if it does the transformation directly in the original document and not in a _formatted version.)

**Comment by MarinPostma** [comment]
this is fixed by #150 and #157
