### ISSUE TITLE
integrate the new rankingRules

### ISSUE THREAD

**Issue by curquiza** [meilisearch/transplant#85]
Integrate the new ranking rules in settings.

The new ranking rules are:

```
[
  "words",
  "typo",
  "proximity",
  "attribute",
  "exactness"
]
```

(wordsPosition does not exist anymore, and the order changed for `typo`)

**Comment by MarinPostma** [comment]
closed through #58

**Comment by curquiza** [comment]
I've just tested the alpha1 and the `main` branch and the criteria are still the old ones. I re-open the issue :)

**Comment by curquiza** [comment]
@Kerollmops is the description of the current ranking rules correct for you? https://docs.meilisearch.com/learn/core_concepts/relevancy.html#ranking-rules

**Comment by curquiza** [comment]
I updated the issue, checked with @gmourier and the core-team, the `exactness` criterion has been renamed into `exact`.
